#!/bin/bash
yum install -y httpd
echo "Env Var: $DEPLOYMENT_GROUP_NAME"
if [ "$DEPLOYMENT_GROUP_NAME" == "DeploymentGroupTest" ]
then
    if [ -f /var/www/html/index.html ]; then mv -f /var/www/html/index.html /var/www/html/test/; fi
else
    if [ -f /var/www/html/index.html ]; then mv -f /var/www/html/index.html /var/www/html/prod/; fi
fi

